scribbler:
	gcc \
		src/main.c \
		src/objects/graphics.c \
		src/objects/game.c \
		src/objects/room.c \
		src/objects/font.c \
		src/objects/globals.c \
		src/objects/IoHandler.c \
		src/events/ScenarioManager.c \
		src/events/Trigger.c \
		src/events/triggers/InteractEntityTrigger.c \
		src/ECS/Components.c \
		src/ECS/ECS.c \
		src/ECS/MoveComponent.c \
		src/ECS/SpriteComponent.c \
		src/ECS/MappedComponent.c \
		src/ECS/JourneyComponent.c \
		src/ECS/AnimateComponent.c \
		src/ECS/ClickComponent.c \
		src/ECS/InteractComponent.c \
		src/solver.c \
		-lSDL2main \
		-lSDL2 \
		-lSDL2_image \
		-liovmall \
		-ldl \
		-lm \
		-Wall \
		-o \
	scribbler.bin
